
package Vistas;

import accesoADatos.PasajeData;
import accesoADatos.RutaData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Entidades.*;
import accesoADatos.HorarioData;
import java.util.ArrayList;
import jdk.internal.org.jline.utils.InfoCmp;

/**
 *
 * @author Deb APBT
 */
public class PasajesVendidos extends javax.swing.JInternalFrame {

    private List<Ruta> rutaR;
    private List<Pasaje> pasajeP;
    private List<Horario> horarioH;
    
    
    private RutaData rutaData;
    private PasajeData pasajData;
    private HorarioData horarioD;
    
    private DefaultTableModel modelo;
    
    
    /**
     * Creates new form PasajesVendidos
     */
    public PasajesVendidos() {
        initComponents();
        
        rutaData = new RutaData();
        pasajData = new PasajeData();
        rutaR = rutaData.listarRuta();
        horarioD = new HorarioData();
        
        horarioH = horarioD.obtenerTodosLosHorarios();
        
        modelo = new DefaultTableModel();
        
        cargarRutas();
        armarCabecera();
        cargarHorarios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaPV = new javax.swing.JTable();
        jcbFiltrarPorRuta = new javax.swing.JComboBox();
        JCBFiltrarPorHorario = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pasajes Vendidos");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setText("Salir");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pasajes Vendidos");
        jLabel10.setToolTipText("");
        jLabel10.setAlignmentY(0.0F);
        jLabel10.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), null));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Filtrar por Ruta");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Filtrar Por Horario");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Filtrar Por Pasajero");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTablaPV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaPV);

        jcbFiltrarPorRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbFiltrarPorRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltrarPorRutaActionPerformed(evt);
            }
        });

        JCBFiltrarPorHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JCBFiltrarPorHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBFiltrarPorHorarioActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(111, 111, 111)
                .addComponent(jButton1)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbFiltrarPorRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBFiltrarPorHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbFiltrarPorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBFiltrarPorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTON SALIR
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // BORRA FILAS TABLA
    private void borrarFilasTabla() {

        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }
    
    //ARMA CABECERA DE TABLA
    private void armarCabecera() {

        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Id");
        filaCabecera.add("Ruta");
        filaCabecera.add("Fecha de Viaje");
        filaCabecera.add("Hora de Viaje");

        for (Object it : filaCabecera) {

            modelo.addColumn(it);
        }
        
        jTablaPV.setModel(modelo);
    }
    
    // CARGAR RUTAS EN COMBO BOX
    private void cargarRutas() {

        for (Ruta item : rutaR) {

            jcbFiltrarPorRuta.addItem(item);
        }
    }
    
    private void cargaDatosPorRuta() {

        Ruta select = (Ruta) jcbFiltrarPorRuta.getSelectedItem();
        List<Pasaje> lista = pasajData.obtenerPasajeVendidoPorRuta(select.getIdRuta());

        for (Pasaje a : lista) {

            modelo.addRow(new Object[]{a.getIdPasaje(), a.getRuta(), a.getFechaViaje(), a.getHoraViaje()});
            
            
        }
        modelo.fireTableDataChanged();
        
    }
    
    // CARGAR HORARIOS EN COMBO BOX
    private void cargarHorarios() {

        for (Horario item : horarioH) {

            JCBFiltrarPorHorario.addItem(item);
        }
    }
    
    private void cargaDatosPorHorario() {

        Horario select = (Horario) JCBFiltrarPorHorario.getSelectedItem();
        List<Pasaje> lista = pasajData.obtenerPasajeVendidoPorHorario(select.getHoraSalida());

        for (Pasaje b : lista) {

            modelo.addRow(new Object[]{b.getIdPasaje()});
        }
        modelo.fireTableDataChanged();
    }
    
    
    private void jcbFiltrarPorRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltrarPorRutaActionPerformed
        
        borrarFilasTabla();
        cargaDatosPorRuta();
        
    }//GEN-LAST:event_jcbFiltrarPorRutaActionPerformed

    private void JCBFiltrarPorHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBFiltrarPorHorarioActionPerformed
        
        borrarFilasTabla();
        cargaDatosPorHorario();
        
    }//GEN-LAST:event_JCBFiltrarPorHorarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCBFiltrarPorHorario;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaPV;
    private javax.swing.JComboBox jcbFiltrarPorRuta;
    // End of variables declaration//GEN-END:variables
}
